# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: ubuntu-22.04
   tools:
      python: "3.10" # python-control 0.10.0 requires Python > 3.9
   apt_packages:
      # dependencies for chrome and firefox
      - bzip2
      - libxtst6
      - libgtk-3-0
      - libx11-xcb-dev
      - libdbus-glib-1-2
      - libxt6
      - libpci-dev
      - libasound2
      # dependencies for slycot
      - gfortran
      - cmake
      - libblas-dev
      - liblapack-dev
   jobs:
      pre_install:
         - mkdir $HOME/selenium
         - mkdir $HOME/selenium/drivers
         # chrome
         - wget -N https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation\=1663284576100523\&alt\=media -P $HOME
         - unzip ~/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation=1663284576100523\&alt=media -d $HOME/selenium
         - rm ~/Linux_x64%2F1047731%2Fchrome-linux.zip\?generation=1663284576100523\&alt=media
         - wget -N https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_linux64.zip -P $HOME
         - unzip ~/chromedriver_linux64.zip -d $HOME/selenium/drivers
         - rm ~/chromedriver_linux64.zip
      post_install:
         - pip install "panel==1.3.8" # NOTE: remove it when this is solved: https://github.com/holoviz/panel/issues/6643
         - pip install --no-cache-dir slycot
      #    - pip install "matplotlib<3.6.0"
      # post_build:
      #    - cat $HOME/selenium/sphinx_k3d_screenshot.log

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/source/conf.py

# Optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
   - requirements: doc/requirements.txt
   - method: pip
     path: .
   - method: pip
     path: .
     extra_requirements:
        - all
